In [5]:
import numpy as np


In [ ]:
a = np.array([1,2, 3, 4, 5, 6])
a
a[2] = 10
a[2]

10

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 100, 11) # creates array with evenly spaced elements in a given range


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Multi-dimensional array

In [ ]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [ ]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n[:, 2] = [0, 1, 2]
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

In [ ]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Randomly generated array

In [ ]:
np.random.seed(3)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

Element-wise Operation


In [7]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [8]:
b = 10 +(a*2)
b

array([10, 12, 14, 16, 18])

In [9]:
a>=3

array([False, False, False,  True,  True])

In [10]:
a.std()

1.4142135623730951

In [13]:
a.max()

4

In [11]:
a.min()

0

In [12]:
a.sum()

10